# Generated by Django 5.1.4 on 2025-01-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='images',
        ),
        migrations.RemoveField(
            model_name='gymproduct',
            name='images',
        ),
        migrations.CreateModel(
            name='GymImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gyms/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gym_images', to='gym_management.gym')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='gym_management.gymproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
