# Generated by Django 5.1.4 on 2025-02-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_management', '0003_gym_created_at_gym_updated_at_gymplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymplan',
            name='duration',
            field=models.IntegerField(help_text='Duration in days', null=True),
        ),
    ]
