# Generated by Django 5.1.4 on 2025-02-15 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym_management', '0003_gym_created_at_gym_updated_at_gymplan_created_at_and_more'),
        ('users', '0004_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymMembersByOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('photo', models.ImageField(upload_to='members/photos/')),
                ('documents', models.FileField(upload_to='members/documents/')),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.address')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_members', to='gym_management.gym')),
            ],
        ),
    ]
