# Generated by Django 5.1.4 on 2025-02-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymmembersbyowner',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='members/documents/'),
        ),
        migrations.AlterField(
            model_name='gymmembersbyowner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/'),
        ),
    ]
