# Generated by Django 5.1.4 on 2025-02-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_members', '0002_alter_gymmembersbyowner_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymmembersbyowner',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gymmembersbyowner',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymmembersbyowner',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
